spring.datasource.url=${SPRING_DATASOURCE_URL:${MYSQL_URL:jdbc:h2:mem:chatbox;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${MYSQL_USER:sa}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${MYSQL_PASSWORD:}}
spring.h2.console.enabled=false
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
